name: DevOps CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java application
        run: javac HelloWorld.java

      - name: Run Java application
        run: java HelloWorld

      - name: Build Docker image
        run: docker build -t devops-demo .